version: "3.8"

services:
  db:
    image: postgres:13
    container_name: the_desk_service_db # <-- ZMIANA
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=the_desk_service # <-- ZMIANA
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: the_desk_service_backend # <-- ZMIANA
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/the_desk_service # <-- ZMIANA

  frontend:
    build: ./frontend
    container_name: the_desk_service_frontend # <-- ZMIANA
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "7050:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
